### ISSUE TITLE
$(gimme-aws-creds) doesn't work on zsh

### ISSUE THREAD

**Issue by cloudlena** [Nike-Inc/gimme-aws-creds#156] opened 2019-12-03 10:09 UTC
When running `$(gimme-aws-creds)` on zsh, I get the following error: `zsh: command not found: #`.

## Expected Behavior

I expect this command to also work on zsh.

## Current Behavior

The above described error occurs and the env variables are not set.

## Possible Solution

Remove the comment from the output or make it dependent on the shell being used (i.e. `$SHELL`).

## Steps to Reproduce (for bugs)

1. Use `zsh` as the shell
2. Run `$(gimme-aws-creds)`

## Context

I had to run `gimme-aws-creds` and then copy the output and run it manually.

## Your Environment

* App Version used: gimme-aws-creds 2.1.3
* Environment name and version: zsh 5.7.1
* Operating System and version: macOS 10.15.1

**Comment by JDTAY** [comment] 2019-12-03 23:43
Not sure if I had this problem on my install Catalina. I'll be wiping my Mac this weekend so I'll re-test gimme on a clean install.

**Comment by bethleha** [comment] 2019-12-12 08:54
https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/main.py#L181

In the above line a string output to the stdout is the cause of the issue. Typically there are two lines logged to the stdout prior to the export statements are the cause of this issue, I think.

```
Saving arn:aws:iam::<account-id>:role/<role-name> as <role-name>
Written profile <role-name> to /Users/<username>/.aws/credentials
```

**Comment by JDTAY** [comment] 2019-12-17 04:39
I've got a fresh install of Catalina on my Mac, I don't this behavior on iTerm2 & Terminal.

**Comment by mastertinner** [comment] 2019-12-17 09:11
I just checked again and I'm still getting the problem. However, I couldn't tell you what's different to yours. My whole setup is here: https://github.com/mastertinner/dotfiles/
@JDTAY, thanks a lot for checking! Could you see if you can spot any difference from your setup to mine that might be significant here?
If not, I would suggest to just close this issue because I cannot tell how to reproduce it on other systems.

**Comment by JDTAY** [comment] 2019-12-17 23:54
Well at the very least, I ought to set up on my dotfile repo @mastertinner!
I'll go about configuring mine and perform a comparison against your own.

**Comment by BaptisteTamedia** [comment] 2020-02-11 08:05
Quick fix could be to comment https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/main.py#L788

**Comment by biocdeniz** [comment] 2020-03-16 15:19
I have found similar issues when using `zsh` and I often get the `zsh: command not found:` error (with this and other packages). My quick fix, consistently working, has been to create a conda/miniconda environment, and to install and execute packages within that environment.

### Setup/Environment
* MacOS 10.14.6
* gimme-aws-creds 2.3.1
* zsh 5.3
* conda 4.8.2
* Python 3.7.3

**Comment by larryon** [comment] 2020-04-16 11:05
Added PR https://github.com/Nike-Inc/gimme-aws-creds/pull/192

**Comment by ramiro** [comment] 2020-04-20 15:10
This isn't happening just on zsh. I see it on Bash 5.x installed on Macos Mojave 10.14.6 via Brew (gimme-aws-creds version is 2.3.3):

```
$ which bash
/usr/local/bin/bash

$ echo $0
-bash

$ echo $BASH_VERSION
5.0.11(1)-release

$ $(gimme-aws-creds)
Username: user@example.com
Using password from keyring for user@example.com
Okta Password for user@example.com:
Do you want to save this password in the keyring? (y/n) n
Multi-factor Authentication required.
web: Duo selected
Duo required; opening browser...
-bash: #: command not found

$ gimme-aws-creds --version
gimme-aws-creds 2.3.3
```

**Comment by larryon** [comment] 2020-04-21 06:54
@ramiro Can you check my PR ?

**Comment by ramiro** [comment] 2020-04-21 12:40
> @ramiro Can you check my PR ?

It works. Thanks!

**Comment by Tyler-2** [comment] 2020-05-18 18:57
Debian bash shell, same problem. PR looks good.

**Comment by Tyler-2** [comment] 2020-05-18 19:03
BTW a simple workaroud until the PR is rolled in:
`$(gimme-aws-creds | grep '^EXPORT')`

**Comment by slaffcheff** [comment] 2020-07-20 11:17
This is still happening on Ubuntu 20.04 .. :( 

`╭─rogue@work-450-G7 ~ 
╰─$ which bash                                                            127 ↵
/usr/bin/bash
╭─rogue@work-450-G7 ~ 
╰─$ echo $0                
/bin/zsh
╭─rogue@work-450-G7 ~ 
╰─$ echo $ZSH_VERSION      
5.8
╭─rogue@work-450-G7 ~ 
╰─$ $(gimme-aws-creds)     
zsh: command not found: gimme-aws-creds
`
Everything is freshly installed so latest stable versions are installed on the machine.

**Comment by larryon** [comment] 2020-07-20 11:59
can you try `which gimme-aws-creds` ?

**Comment by slaffcheff** [comment] 2020-07-20 13:01
> gimme-aws-creds

```
$ which gimme-aws-creds
gimme-aws-creds not found
```

what i did was pip3 install following the instructions.

**Comment by larryon** [comment] 2020-07-20 13:18
did you run it with sudo?

**Comment by slaffcheff** [comment] 2020-07-20 13:23
No, just `pip3 install --upgrade gimme-aws-creds`.

**Comment by larryon** [comment] 2020-07-20 13:25
try `pip3 install --upgrade git+git://github.com/Nike-Inc/gimme-aws-creds.git`

**Comment by slaffcheff** [comment] 2020-07-20 13:27
`Successfully built gimme-aws-creds
Installing collected packages: gimme-aws-creds
  Attempting uninstall: gimme-aws-creds
    Found existing installation: gimme-aws-creds 2.3.4
    Uninstalling gimme-aws-creds-2.3.4:
      Successfully uninstalled gimme-aws-creds-2.3.4
Successfully installed gimme-aws-creds-2.3.4
`

`$ gimme-aws-creds
zsh: command not found: gimme-aws-creds`

Unfortunately, not working .. Is it possible zsh issue?

**Comment by MSBlueVn** [comment] 2023-05-14 07:27
Installed via pip3 on macOS 13.3.1, and I got the same error on bash.
Should I open a new ticket, or should it stay on this one?

**Comment by epierce** [comment] 2023-05-15 17:56
The original problem (running `$(gimme-aws-creds)` failed) has been fixed.  However, if you run `which gimme-aws-creds` and get "command not found", the issue is with your PATH and you need to update it as mention by @larryon above

**Closed by epierce** 2023-05-15 17:56 UTC

**Comment by MSBlueVn** [comment] 2023-05-16 04:10
I did put it in the PATH, but still got nothing. There's no bin when you install via pip3, so I made sure the location of the python scripts as reported by pip3 show was in the path, but still got command not found.

I opened a separate issue for this.
