### ISSUE TITLE
error after accepting pop up.

### ISSUE THREAD

**Issue by mlybarger** [Nike-Inc/gimme-aws-creds#304] opened 2021-06-29 14:25 UTC
i'm using linux mint.  when running gimme-aws-creds, i get this traceback.  not quite sure how to resolve. any help is most certainly appreciated.  this was working a few days back until maybe updates.  i tried uninstalling gimme-aws-creds and re-installing using pip3 install/uninstall gimme-aws-creds.

Multi-factor Authentication required.
Okta Verify App: SmartPhone_Android: SM-N960U selected
Okta Verify push sent...
Traceback (most recent call last):
  File "/home/mark/.local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 469, in run
    self._run()
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 802, in _run
    for data in self.iter_selected_aws_credentials():
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 773, in iter_selected_aws_credentials
    for role in self.aws_selected_roles:
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 672, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 663, in aws_roles
    self.saml_data['SAMLResponse'],
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 654, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 647, in aws_app
    self._cache['aws_app'] = aws_app = self._get_selected_app(self.conf_dict.get('aws_appname'), self.aws_results)
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 600, in aws_results
    self.auth_session
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 582, in auth_session
    auth_result = self.okta.auth_session()
  File "/home/mark/.local/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 183, in auth_session
    "session": response.cookies['sid'],
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='sid', domain=None, path=None"

... update. i'm getting the same error on windows as well.

**Comment by m-pabon** [comment] 2021-06-29 14:35
Seeing same issue on macos. This started happening after I updated my okta password.

**Comment by mlybarger** [comment] 2021-06-29 15:16
found a fix which required modifying main.py as:

    @property
    def auth_session(self):
        if 'auth_session' in self._cache:
            return self._cache['auth_session']
        auth_result = self.okta.auth_session(redirect_uri=self.conf_dict.get('app_url'))
        self.set_auth_session(auth_result)
        return auth_result

this fixed the issue for me.  maybe i can see about a pull request.

**Comment by ChristophShyper** [comment] 2021-06-29 15:39
Also, it's a duplicate of https://github.com/Nike-Inc/gimme-aws-creds/issues/302

**Closed** 2021-06-29 20:47 UTC
