### ISSUE TITLE
Problem if wrong password entered after reset

### ISSUE THREAD

**Issue by roboweaver** [Nike-Inc/gimme-aws-creds#160] opened 2020-01-03 19:34 UTC
Changed my Okta password, and as expected the gimme-aws-creds call first failed, then prompted me for a new password.

I entered the old password by accident, which got written to the Keychain `gimme-aws-creds` entry. 

This resulted in an error I couldn't get around until I updated the Keychain entry with the proper password (I suppose I could have removed the entry from the Keychain as well).
## Expected Behavior

Ideally, when the password fails, it should always prompt for the password to be entered, and it shouldn't write the password to the Keychain until it has successfully logged in.

## Current Behavior

When login fails after password change, the login fails. User must run `gimme-aws-creds` a second time to get the password prompt. There is a question asking if this should be written to the Keychain, but the password is not validated prior to the write leaving the client in a bad state.

## Possible Solution

Don't write the password to keychain until after it succeeds.
And probably always prompt for the password when the one in the Keychain fails.

## Steps to Reproduce (for bugs)

1. Change the password in the Keychain to something bogus OR change your Okta password
2. Run gimme-aws-creds
3. If prompted for password, give it a bad password
4. Once the bad password is in the Keychain, you should see something like:

```Robs-Mac-Pro:verify-stewards robweaver$ gimme-aws-creds
Using password from keyring for robweaver@workfront.com
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 447, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 738, in _run
    for data in self.iter_selected_aws_credentials():
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 714, in iter_selected_aws_credentials
    for role in self.aws_selected_roles:
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 632, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 623, in aws_roles
    self.saml_data['SAMLResponse'],
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 614, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 607, in aws_app
    self._cache['aws_app'] = aws_app = self._get_selected_app(self.conf_dict.get('aws_appname'), self.aws_results)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 560, in aws_results
    self.okta.auth_session()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/okta.py", line 156, in auth_session
    login_response = self.auth()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/okta.py", line 145, in auth
    flow_state = self._login_username_password(None, self._okta_org_url + '/api/v1/authn')
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/okta.py", line 336, in _login_username_password
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://workfront.okta.com/api/v1/authn```

<!-- And so on -->

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* App Version used: gimme-aws-creds 2.2.0 (was also using 2.1.0 prior to having this issue)
* Environment name and version:
* Operating System and version: Mac OS X

**Comment by sf182k** [comment] 2020-01-06 19:31
This not only applies to incorrectly typed saved passwords, but also applies to any password that was typed correctly and then subsequently expired causing it to be invalid.  

OS X Workarounds:

- Open up keychain and kill the gimme-aws-creds entry using the UI
- Use keyring set gimme-aws-creds foo@bar.com from the terminal

**Comment by Sector95** [comment] 2020-01-13 22:40
Hmm it's not clear to me why this behavior started, but I just ran into it last week too.

**Comment by bbergstrom** [comment] 2020-01-31 17:19
I'm not sure when it started either, but we are experiencing this issue as well when a user resets their password triggered by expiration.

**Comment by twelvelabs** [comment] 2020-02-05 17:31
Looks like a regression introduced in 29f5eef80e9dc3107083caf12364f37e26f5fa79 - the `raise_for_status` line [here](https://github.com/Nike-Inc/gimme-aws-creds/blame/f2b911981bcd3deaf4fcdfcd2557b317f94aa997/gimme_aws_creds/okta.py#L336) is preventing the expired password from being removed from the keyring on auth failure.

**Comment by Sector95** [comment] 2020-02-06 19:37
This has been fixed in v2.3.1, thanks!

**Closed by Sector95** 2020-02-06 19:37 UTC
Labels: bug

**Comment by ashish-akshantal** [comment] 2021-07-13 15:38
> This not only applies to incorrectly typed saved passwords, but also applies to any password that was typed correctly and then subsequently expired causing it to be invalid.
> 
> OS X Workarounds:
> 
> * Open up keychain and kill the gimme-aws-creds entry using the UI
> * Use keyring set gimme-aws-creds [foo@bar.com](mailto:foo@bar.com) from the terminal

How can we force gimme-aws-creds to enter password everytime without storing it in Keyring ? I dont have access to keyring and I assume I entered a incorrect password. I need to renter the correct password. 
I am running this command gimme-aws-creds --profile my-profile --register_device

**Comment by PaulForgey-Discovery** [comment] 2022-01-10 16:11
This is annoyingly happening in 2.4.3 after a password change. Any application using the keychain should fall back to a prompt and offer to update the keychain entry if the stored password is wrong.

**Comment by roboweaver** [comment] 2022-01-14 23:56
> This is annoyingly happening in 2.4.3 after a password change. Any application using the keychain should fall back to a prompt and offer to update the keychain entry if the stored password is wrong.

The first failure clears out the keychain, so you just have to run the command again

**Comment by bschatz12** [comment] 2022-02-07 05:22
roboweaver -  nothing of the sort happens

**Comment by roboweaver** [comment] 2022-02-09 20:27
@bschatz12 - Not sure what you mean by that - I have never had a problem with password reset other than remembering to run the command a second time in order to put the new password in place. Used to have to go into the keychain and manually find the password entry before they fixed that.

**Comment by roboweaver** [comment] 2022-03-23 21:32
Same for sure - I haven't seen any cases where the keychain doesn't get cleared out.
