### ISSUE TITLE
Can't have more than one profile? Keeps overwriting.

### ISSUE THREAD

**Issue by wbirkmaier** [Nike-Inc/gimme-aws-creds#102] opened 2019-01-25 05:32 UTC
When I do `gimme-aws-creds --configure --profile Environment1 `that works fine. if I repeat the command with `Environment2`, the old `Enviroment1 `entry is now gone from the .okta_aws_login_config file.

Am I doing something wrong or is this a bug? The same happens when you do `--register_device --profile Environment1`. I tried editing the file by hand, and it works for logging into each environment, after I concatenated the two separate files I saved to the side. But again if I do any register or config commands it wipes the file.

I am using the appurl mode if this matters.

Thank you.

**Comment by wbirkmaier** [comment] 2019-01-29 15:31
I have looked through the code, the code states to always overwrite the file when creating the .okta... file. So will dig a bit deeper to see why it is not rebuilding the whole file. If I change the code to append that works but then you can't make changes, only add new profiles.

**Comment by Sector95** [comment] 2019-01-30 19:09
Looks like a duplicate of #77.  Closing to consolidate.

**Closed by Sector95** 2019-01-30 19:09 UTC
Labels: bug
